language: cpp

matrix:
  include:
    - os: windows
      env: BUILD_CONFIGURATION=Debug
    - os: windows
      env: BUILD_CONFIGURATION=Release
    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'gcc-9', 'doxygen', 'doxygen-doc', 'doxygen-latex', 'doxygen-gui', 'graphviz']
      env: 
         - GCCVER='9' CXX_COMPILER=g++-${GCCVER} C_COMPILER=gcc-${GCCVER} AR=gcc-ar-${GCCVER} RANLIB=gcc-ranlib-${GCCVER} NM=gcc-nm-${GCCVER} BUILD_CONFIGURATION=Debug
         - GCCVER='9' CXX_COMPILER=g++-${GCCVER} C_COMPILER=gcc-${GCCVER} AR=gcc-ar-${GCCVER} RANLIB=gcc-ranlib-${GCCVER} NM=gcc-nm-${GCCVER} BUILD_CONFIGURATION=Release
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Debug
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - . ../.travis/build.sh
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then oxygen 2>&1 > doxygen.log || cat doxygen.log ; fi
  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/  
  on:
    branch: master

# FIXME: (alkurbatov): Temporary disable documentation generator.
# This should be changed as we don't want/can push to Blizzard repos.
#after_success:
#  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd $TRAVIS_BUILD_DIR && ./generate_and_deploy_doxygen.sh'
